# Generated by Django 4.2.27 on 2026-01-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird_watch', '0002_bird_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bird',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
