# Generated by Django 4.2.27 on 2026-01-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird_watch', '0004_alter_bird_created_by_alter_bird_slug_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='bird_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
