# Generated by Django 4.2.27 on 2026-01-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird_watch', '0005_entry_bird_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='body',
            field=models.CharField(max_length=200),
        ),
    ]
