# Generated by Django 4.2.27 on 2026-01-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird_watch', '0006_alter_entry_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='status',
            field=models.IntegerField(choices=[(1, 'Published')], default=1),
        ),
    ]
