# Generated by Django 4.2.27 on 2026-01-21 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird_watch', '0007_alter_bird_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='bird_name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Bird name can only contain letters and spaces.', regex='^[a-zA-Z\\s]+$')]),
        ),
    ]
