# Generated by Django 4.2.27 on 2026-05-14 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bird_watch', '0008_alter_bird_bird_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='status',
        ),
    ]
